resources:
  repositories:
  - repository: memesfinder-infrastructure
    type: github
    name: ArtemKiyashko/memesfinder-infrastructure
    endpoint: github.com_ArtemKiyashko
    
trigger:
  branches:
    include:
    - master
    - development
  paths:
    exclude:
    - 'README.md'
    - 'img/'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Test
  jobs:
   - job: Deploy
     steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Deploy resource group
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Azure Vostok (60447d26-d388-4a2b-a8cd-45114f7099a8)'
          subscriptionId: '60447d26-d388-4a2b-a8cd-45114f7099a8'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'testgroup'
          location: 'West Europe'
          templateLocation: 'Linked artifact'
          csmFile: 'template.json'
          csmParametersFile: 'envs/test/parameters.json'
          deploymentMode: 'Incremental'
- stage: Production
  dependsOn: Test
  condition: and(succeeded('Test'), ne(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
   - job: Deploy
     steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Deploy resource group
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Azure Vostok (60447d26-d388-4a2b-a8cd-45114f7099a8)'
          subscriptionId: '60447d26-d388-4a2b-a8cd-45114f7099a8'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'rsgweprivatememesfinder'
          location: 'West Europe'
          templateLocation: 'Linked artifact'
          csmFile: 'template.json'
          csmParametersFile: 'envs/prod/parameters.json'
          deploymentMode: 'Incremental'

